// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfYY4pKnvB64AkB8Vavsq_UZEvEsMln2g',
    appId: '1:798890786938:web:b78de0dccd3a797488fbc3',
    messagingSenderId: '798890786938',
    projectId: 'growell-bd677',
    authDomain: 'growell-bd677.firebaseapp.com',
    storageBucket: 'growell-bd677.firebasestorage.app',
    measurementId: 'G-5DY0020V7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3IpfQCLLcqXHOcHEDPOAO1xbZMlIc2AA',
    appId: '1:798890786938:android:120e1e705da74fa388fbc3',
    messagingSenderId: '798890786938',
    projectId: 'growell-bd677',
    storageBucket: 'growell-bd677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ocPTH0RXoylHLz5Rjln4qSfTWI8VTDw',
    appId: '1:798890786938:ios:b72616d2ad5b377888fbc3',
    messagingSenderId: '798890786938',
    projectId: 'growell-bd677',
    storageBucket: 'growell-bd677.firebasestorage.app',
    iosBundleId: 'com.example.growell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ocPTH0RXoylHLz5Rjln4qSfTWI8VTDw',
    appId: '1:798890786938:ios:b72616d2ad5b377888fbc3',
    messagingSenderId: '798890786938',
    projectId: 'growell-bd677',
    storageBucket: 'growell-bd677.firebasestorage.app',
    iosBundleId: 'com.example.growell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfYY4pKnvB64AkB8Vavsq_UZEvEsMln2g',
    appId: '1:798890786938:web:4f167da86a41adbb88fbc3',
    messagingSenderId: '798890786938',
    projectId: 'growell-bd677',
    authDomain: 'growell-bd677.firebaseapp.com',
    storageBucket: 'growell-bd677.firebasestorage.app',
    measurementId: 'G-KYWN1S6VX7',
  );
}
